baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Research
      url: "research/"
      weight: 3
    - name: GeoTutor
      url: "geotutor/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "All content &copy; Abigail S. Knapp 2021 unless otherwise noted. | [Github](https://github.com/askgeo) | [Twitter](https://twitter.com/geoabby) <br>Theme &copy; [Yihui Xie](https://yihui.org)."

markup:
  goldmark:
    renderer:
      unsafe: true
