baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Welcome
      url: "welcome/"
      weight: 1
    - name: About
      url: "about/"
      weight: 4
    - name: Research
      url: "research/"
      weight: 2
    - name: GeoTutor
      url: "geotutor/"
      weight: 3
    - name: Photos
      url: "photos/"
      weight: 5
    - name: Blog
      url: ""
      weight: 6

params:
  description: "A.S.K. Geology"
  footer: "[Github](https://github.com/askgeo) | [Twitter](https://twitter.com/geoabby) | [LinkedIn](https://www.linkedin.com/in/askgeology/) | [Thingiverse](https://www.thingiverse.com/asknapp/designs)<br> &copy; Abigail S. Knapp 2021 unless otherwise cited or licensed. <br> Theme &copy; [Yihui Xie](https://yihui.org) 2020."

markup:
  goldmark:
    renderer:
      unsafe: true
